// summary.go — AI-generated dashboard summary endpoint for OpenGuard v5.
// POST /api/v1/summary accepts a snapshot of current dashboard data and returns
// a natural-language summary generated by whichever AI provider is active.
// Results are cached for 60 seconds so rapid refreshes don't incur extra cost.
package consoleapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"sync"
	"time"

	"go.uber.org/zap"
)

// SummaryRequest is the payload sent by the frontend.
type SummaryRequest struct {
	TotalEvents    int     `json:"total_events"`
	TotalIncidents int     `json:"total_incidents"`
	CPUUtilPct     float64 `json:"cpu_util_pct"`
	MemUsedPct     float64 `json:"mem_used_pct"`
	LoadAvg1       float64 `json:"load_avg_1m"`
	// Top event types and their counts.
	TopEventTypes []EventTypeStat `json:"top_event_types"`
	// Tier breakdown (T0–T4 counts).
	TierBreakdown []TierStat `json:"tier_breakdown"`
	// Incident statuses.
	IncidentStatuses []IncidentStatusStat `json:"incident_statuses"`

	// HostGuard module stats.
	HostTotalEvents  int `json:"host_total_events"`
	HostThreatEvents int `json:"host_threat_events"`
	HostUniqueHosts  int `json:"host_unique_hosts"`
	HostActiveRules  int `json:"host_active_rules"`

	// AgentGuard module stats.
	AgentTotalAgents    int `json:"agent_total_agents"`
	AgentActiveAgents   int `json:"agent_active_agents"`
	AgentSuspended      int `json:"agent_suspended_count"`
	AgentQuarantined    int `json:"agent_quarantine_count"`
	AgentTotalThreats   int `json:"agent_total_threats"`

	// ModelGuard module stats.
	ModelTotalCalls    int     `json:"model_total_calls"`
	ModelBlockedCalls  int     `json:"model_blocked_calls"`
	ModelAvgLatencyMs  float64 `json:"model_avg_latency_ms"`
	ModelAvgConfidence float64 `json:"model_avg_confidence"`
	ModelRiskBreakdown []TierStat `json:"model_risk_breakdown"`

	// CommsGuard module stats.
	CommsTotalEvents    int            `json:"comms_total_events"`
	CommsTotalThreats   int            `json:"comms_total_threats"`
	CommsTopEventTypes  []EventTypeStat `json:"comms_top_event_types"`

	// Per-module threat / anomaly breakdowns.
	HostTopEventTypes  []EventTypeStat `json:"host_top_event_types"`
	AgentTopEventTypes []EventTypeStat `json:"agent_top_event_types"`
}

// EventTypeStat is a (type, count) pair.
type EventTypeStat struct {
	Type  string `json:"type"`
	Count int    `json:"count"`
}

// TierStat is a (tier, count) pair.
type TierStat struct {
	Tier  string `json:"tier"`
	Count int    `json:"count"`
}

// IncidentStatusStat is a (status, count) pair.
type IncidentStatusStat struct {
	Status string `json:"status"`
	Count  int    `json:"count"`
}

// SummaryResponse is what the endpoint returns.
type SummaryResponse struct {
	Summary      string `json:"summary"`
	Provider     string `json:"provider"`
	GeneratedAt  string `json:"generated_at"`
	CacheHit     bool   `json:"cache_hit"`
}

// summaryCacheEntry holds a cached summary response and its expiry.
type summaryCacheEntry struct {
	resp      SummaryResponse
	expiresAt time.Time
}

// summaryCache is a per-user TTL cache for generated summaries.
type summaryCache struct {
	mu      sync.Mutex
	entries map[string]summaryCacheEntry // key: username
}

var globalSummaryCache = &summaryCache{entries: make(map[string]summaryCacheEntry)}

// handleSummary handles POST /api/v1/summary.
func (s *Server) handleSummary(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	body, err := io.ReadAll(io.LimitReader(r.Body, 64*1024))
	if err != nil {
		http.Error(w, "failed to read body", http.StatusBadRequest)
		return
	}

	var req SummaryRequest
	if err := json.Unmarshal(body, &req); err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": "invalid request body"})
		return
	}

	username, _ := r.Context().Value(contextKeyActor).(string)
	activeProvider, _ := s.activeProvider.Load().(string)

	// Check per-user cache.
	globalSummaryCache.mu.Lock()
	if entry, ok := globalSummaryCache.entries[username]; ok && time.Now().Before(entry.expiresAt) {
		cached := entry.resp
		cached.CacheHit = true
		globalSummaryCache.mu.Unlock()
		writeJSON(w, http.StatusOK, cached)
		return
	}
	globalSummaryCache.mu.Unlock()

	summary, err := s.generateSummary(r.Context(), username, activeProvider, req)
	if err != nil {
		s.logger.Warn("console api: summary generation failed", zap.Error(err))
		// Return a graceful degraded response rather than an HTTP error.
		writeJSON(w, http.StatusOK, SummaryResponse{
			Summary:     "AI summary unavailable — sign in to a model provider in Model Settings.",
			Provider:    activeProvider,
			GeneratedAt: time.Now().UTC().Format(time.RFC3339),
			CacheHit:    false,
		})
		return
	}

	resp := SummaryResponse{
		Summary:     summary,
		Provider:    activeProvider,
		GeneratedAt: time.Now().UTC().Format(time.RFC3339),
		CacheHit:    false,
	}

	globalSummaryCache.mu.Lock()
	globalSummaryCache.entries[username] = summaryCacheEntry{
		resp:      resp,
		expiresAt: time.Now().Add(60 * time.Second),
	}
	globalSummaryCache.mu.Unlock()

	writeJSON(w, http.StatusOK, resp)
}

// generateSummary retrieves the user's stored credential for the active provider
// and calls the appropriate AI API.
func (s *Server) generateSummary(ctx context.Context, username, provider string, req SummaryRequest) (string, error) {
	credential, err := s.getAccessToken(username, provider)
	if err != nil {
		return "", err
	}
	prompt := buildSummaryPrompt(req)
	switch provider {
	case "anthropic-claude":
		return callClaude(ctx, prompt, credential)
	case "google-gemini":
		return callGemini(ctx, prompt, credential)
	default: // "openai-codex" and anything else
		return callOpenAI(ctx, prompt, credential)
	}
}

// buildSummaryPrompt constructs the LLM prompt from the dashboard snapshot.
func buildSummaryPrompt(req SummaryRequest) string {
	tierLines := ""
	for _, t := range req.TierBreakdown {
		if t.Count > 0 {
			tierLines += fmt.Sprintf("  - %s: %d events\n", t.Tier, t.Count)
		}
	}
	typeLines := ""
	for _, et := range req.TopEventTypes {
		typeLines += fmt.Sprintf("  - %s: %d\n", et.Type, et.Count)
	}
	incidentLines := ""
	for _, is := range req.IncidentStatuses {
		incidentLines += fmt.Sprintf("  - %s: %d\n", is.Status, is.Count)
	}

	hostEventLines := ""
	for _, et := range req.HostTopEventTypes {
		hostEventLines += fmt.Sprintf("  - %s: %d\n", et.Type, et.Count)
	}
	agentEventLines := ""
	for _, et := range req.AgentTopEventTypes {
		agentEventLines += fmt.Sprintf("  - %s: %d\n", et.Type, et.Count)
	}
	commsEventLines := ""
	for _, et := range req.CommsTopEventTypes {
		commsEventLines += fmt.Sprintf("  - %s: %d\n", et.Type, et.Count)
	}
	modelRiskLines := ""
	for _, r := range req.ModelRiskBreakdown {
		modelRiskLines += fmt.Sprintf("  - %s: %d calls\n", r.Tier, r.Count)
	}

	cpuStr := fmt.Sprintf("%.1f%%", req.CPUUtilPct)
	if req.CPUUtilPct < 0 {
		cpuStr = "unavailable"
	}

	modelBlockedPct := 0.0
	if req.ModelTotalCalls > 0 {
		modelBlockedPct = float64(req.ModelBlockedCalls) / float64(req.ModelTotalCalls) * 100
	}

	return fmt.Sprintf(`You are an expert security operations analyst. Write a concise (5–8 sentence) natural-language summary of the current state of the system for a security dashboard. Cover the host, agent, model, and communications security layers as well as overall system health. Highlight any detected threats, anomalies, or patterns of concern and describe the overall security posture. Do NOT output JSON — plain prose only.

Dashboard snapshot:
- Total events captured: %d
- Active incidents: %d
- CPU utilisation: %s  (1-minute load average: %.2f)
- Memory utilisation: %.1f%%

Tier breakdown:
%s
Top event types:
%s
Incident statuses:
%s
HostGuard (endpoint security):
- Total host events: %d  |  Threat events: %d
- Unique hosts monitored: %d  |  Active detection rules: %d
- Host threat / anomaly breakdown:
%s
AgentGuard (AI agent security):
- Total agents: %d  |  Active: %d  |  Suspended: %d  |  Quarantined: %d
- Total agent threats detected: %d
- Agent threat / anomaly breakdown:
%s
ModelGuard (LLM gateway security):
- Total model calls: %d  |  Blocked: %d (%.1f%% block rate)
- Avg latency: %.0f ms  |  Avg confidence: %.0f%%
- Model call risk distribution:
%s
CommsGuard (communications security):
- Total comms events: %d  |  Threats detected: %d
- Top comms threat types:
%s`,
		req.TotalEvents,
		req.TotalIncidents,
		cpuStr, req.LoadAvg1,
		req.MemUsedPct,
		tierLines,
		typeLines,
		incidentLines,
		req.HostTotalEvents, req.HostThreatEvents,
		req.HostUniqueHosts, req.HostActiveRules,
		hostEventLines,
		req.AgentTotalAgents, req.AgentActiveAgents, req.AgentSuspended, req.AgentQuarantined,
		req.AgentTotalThreats,
		agentEventLines,
		req.ModelTotalCalls, req.ModelBlockedCalls, modelBlockedPct,
		req.ModelAvgLatencyMs, req.ModelAvgConfidence*100,
		modelRiskLines,
		req.CommsTotalEvents, req.CommsTotalThreats,
		commsEventLines,
	)
}

// ── Provider call helpers ─────────────────────────────────────────────────────
// Each helper accepts the credential (OAuth2 access token or API key) that was
// retrieved from the user's stored account — environment variables are no longer
// used for per-request authentication.

func callOpenAI(ctx context.Context, prompt, apiKey string) (string, error) {
	if apiKey == "" {
		return "", fmt.Errorf("openai: not connected — sign in via Model Settings")
	}
	body, _ := json.Marshal(map[string]interface{}{
		"model": "gpt-4o",
		"messages": []map[string]string{
			{"role": "user", "content": prompt},
		},
		"max_tokens": 512,
	})
	req, err := http.NewRequestWithContext(ctx, http.MethodPost,
		"https://api.openai.com/v1/chat/completions", bytes.NewReader(body))
	if err != nil {
		return "", err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+apiKey)

	resp, err := (&http.Client{Timeout: 30 * time.Second}).Do(req)
	if err != nil {
		return "", fmt.Errorf("openai request: %w", err)
	}
	defer resp.Body.Close() //nolint:errcheck
	if resp.StatusCode != http.StatusOK {
		b, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("openai status %d: %s", resp.StatusCode, string(b))
	}
	var out struct {
		Choices []struct {
			Message struct {
				Content string `json:"content"`
			} `json:"message"`
		} `json:"choices"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		return "", err
	}
	if len(out.Choices) == 0 {
		return "", fmt.Errorf("openai: empty response")
	}
	return out.Choices[0].Message.Content, nil
}

func callClaude(ctx context.Context, prompt, apiKey string) (string, error) {
	if apiKey == "" {
		return "", fmt.Errorf("anthropic: not connected — sign in via Model Settings")
	}
	body, _ := json.Marshal(map[string]interface{}{
		"model":      "claude-3-5-sonnet-20241022",
		"max_tokens": 512,
		"messages": []map[string]string{
			{"role": "user", "content": prompt},
		},
	})
	req, err := http.NewRequestWithContext(ctx, http.MethodPost,
		"https://api.anthropic.com/v1/messages", bytes.NewReader(body))
	if err != nil {
		return "", err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("x-api-key", apiKey)
	req.Header.Set("anthropic-version", "2023-06-01")

	resp, err := (&http.Client{Timeout: 30 * time.Second}).Do(req)
	if err != nil {
		return "", fmt.Errorf("claude request: %w", err)
	}
	defer resp.Body.Close() //nolint:errcheck
	if resp.StatusCode != http.StatusOK {
		b, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("claude status %d: %s", resp.StatusCode, string(b))
	}
	var out struct {
		Content []struct {
			Type string `json:"type"`
			Text string `json:"text"`
		} `json:"content"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		return "", err
	}
	for _, block := range out.Content {
		if block.Type == "text" {
			return block.Text, nil
		}
	}
	return "", fmt.Errorf("claude: no text content")
}

func callGemini(ctx context.Context, prompt, apiKey string) (string, error) {
	if apiKey == "" {
		return "", fmt.Errorf("google-gemini: not connected — sign in via Model Settings")
	}
	model := "gemini-1.5-pro"
	// Gemini API key authentication uses the ?key= query parameter.
	apiURL := fmt.Sprintf(
		"https://generativelanguage.googleapis.com/v1beta/models/%s:generateContent?key=%s",
		model, apiKey)
	body, _ := json.Marshal(map[string]interface{}{
		"contents": []map[string]interface{}{
			{"parts": []map[string]string{{"text": prompt}}},
		},
		"generationConfig": map[string]interface{}{"maxOutputTokens": 512},
	})
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, apiURL, bytes.NewReader(body))
	if err != nil {
		return "", err
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := (&http.Client{Timeout: 30 * time.Second}).Do(req)
	if err != nil {
		return "", fmt.Errorf("gemini request: %w", err)
	}
	defer resp.Body.Close() //nolint:errcheck
	if resp.StatusCode != http.StatusOK {
		b, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("gemini status %d: %s", resp.StatusCode, string(b))
	}
	var out struct {
		Candidates []struct {
			Content struct {
				Parts []struct {
					Text string `json:"text"`
				} `json:"parts"`
			} `json:"content"`
		} `json:"candidates"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		return "", err
	}
	if len(out.Candidates) > 0 && len(out.Candidates[0].Content.Parts) > 0 {
		return out.Candidates[0].Content.Parts[0].Text, nil
	}
	return "", fmt.Errorf("gemini: empty response")
}
